"""Osmosis and water balance equations."""

"""
Van't Hoff Osmotic Pressure - Osmotic pressure from solute concentration

Source: Quantitative Human Physiology 3rd Edition, Unit 2
"""
from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation, PHYSICAL_CONSTANTS
)
from scripts.index import register_equation
import numpy as np

def compute_osmotic_pressure(C: float, sigma: float = 1.0, R: float = 8.314, T_body: float = 310.0) -> float:
    """
    Calculate osmotic pressure using Van't Hoff equation.

    Formula: π = σ × C × RT

    Parameters:
    -----------
    C : float
        Solute concentration (mol/m³ or mM)
    sigma : float
        Reflection coefficient (0-1), default: 1.0
        σ=1 for ideal semipermeable membrane
        σ=0 for freely permeable
    R : float
        Gas constant (J/(mol·K)), default: 8.314
    T_body : float
        Body temperature (K), default: 310 K (37°C)

    Returns:
    --------
    pi : float
        Osmotic pressure (Pa if C in mol/m³)

    Typical values:
        Plasma osmolarity: ~290 mOsm/L → ~740 kPa (7.4 atm)
    """
    return sigma * C * R * T_body


# Create and register atomic equation
osmotic_pressure = create_equation(
    id="osmotic_pressure",
    output_units='Pa',
    name="Van't Hoff Osmotic Pressure",
    category=EquationCategory.MEMBRANE,
    latex=r"\pi = \sigma \cdot C \cdot RT",
    simplified="pi = sigma * C * R * T",
    description="Osmotic pressure generated by solute concentration across a semipermeable membrane.",
    compute_func=compute_osmotic_pressure,
    parameters=[
        Parameter(
            name="C",
            description="Solute concentration",
            units="mol/m³",
            symbol="C",
            default_value=None,
            physiological_range=(0.0, 1000.0)  # mM
        ),
        Parameter(
            name="sigma",
            description="Reflection coefficient",
            units="dimensionless",
            symbol=r"\sigma",
            default_value=1.0,
            physiological_range=(0.0, 1.0)
        ),
        PHYSICAL_CONSTANTS["R"],
        PHYSICAL_CONSTANTS["T_body"],
    ],
    depends_on=[],
    metadata=EquationMetadata(source_unit=2, source_chapter="2.4")
)

register_equation(osmotic_pressure)

"""
Osmotic Water Flux - Water flow driven by osmotic and hydrostatic gradients

Source: Quantitative Human Physiology 3rd Edition, Unit 2
"""
from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation
)

def compute_water_flux(L_p: float, delta_P: float, delta_pi: float, sigma: float = 1.0) -> float:
    """
    Calculate osmotic water flow (Starling equation).

    Formula: J_V = L_p × (ΔP - σΔπ)

    Parameters:
    -----------
    L_p : float
        Hydraulic conductivity (m/(s·Pa) or cm/(s·mmHg))
    delta_P : float
        Hydrostatic pressure difference (Pa or mmHg)
    delta_pi : float
        Osmotic pressure difference (Pa or mmHg)
    sigma : float
        Reflection coefficient (0-1), default: 1.0

    Returns:
    --------
    J_V : float
        Volume flux (m/s or cm/s)
        Positive flux follows positive ΔP

    Notes:
        Driving force = hydrostatic - osmotic
        Water flows from low to high osmolarity
    """
    return L_p * (delta_P - sigma * delta_pi)


# Create and register atomic equation
water_flux = create_equation(
    id="water_flux",
    output_units='m/s',
    name="Osmotic Water Flux (Starling)",
    category=EquationCategory.MEMBRANE,
    latex=r"J_V = L_p \cdot (\Delta P - \sigma \Delta \pi)",
    simplified="J_V = L_p * (delta_P - sigma * delta_pi)",
    description="Water flow across membrane driven by hydrostatic and osmotic pressure gradients.",
    compute_func=compute_water_flux,
    parameters=[
        Parameter(
            name="L_p",
            description="Hydraulic conductivity",
            units="m/(s·Pa)",
            symbol="L_p",
            default_value=None
        ),
        Parameter(
            name="delta_P",
            description="Hydrostatic pressure difference",
            units="Pa",
            symbol=r"\Delta P",
            default_value=None
        ),
        Parameter(
            name="delta_pi",
            description="Osmotic pressure difference",
            units="Pa",
            symbol=r"\Delta \pi",
            default_value=None
        ),
        Parameter(
            name="sigma",
            description="Reflection coefficient",
            units="dimensionless",
            symbol=r"\sigma",
            default_value=1.0,
            physiological_range=(0.0, 1.0)
        ),
    ],
    depends_on=[],
    metadata=EquationMetadata(source_unit=2, source_chapter="2.4")
)

register_equation(water_flux)

__all__ = ['osmotic_pressure', 'water_flux']


# --- coverage pass additions (Feher extraction) ---

def compute_boyle_vant_hoff_relation(pi_0, pi_C, b):
    """Boyle-van't Hoff relation (Feher Eqn 2.9.3): relative osmometric cell
    volume V_C/V_0 under an anisotonic challenge, from the isotonic-to-anisotonic
    osmotic-pressure (osmolarity) ratio pi_0/pi_C and the osmotically inactive
    volume fraction b = V_b/V_0. pi_0 and pi_C may be in any consistent units
    (Osm/L or Pa) because only their ratio enters; b and the returned volume
    ratio are dimensionless."""
    return (1.0 - b) * (pi_0 / pi_C) + b

boyle_vant_hoff_relation = create_equation(
    id='boyle_vant_hoff_relation',
    output_units='dimensionless',
    name="Boyle-van't Hoff Relation",
    category=EquationCategory.MEMBRANE,
    latex='\\frac{V_C}{V_0} = \\left(1 - \\frac{V_b}{V_0}\\right)\\frac{\\pi_0}{\\pi_C} + \\frac{V_b}{V_0}',
    simplified='V_C/V_0 = (1 - V_b/V_0) * (pi_0/pi_C) + V_b/V_0',
    description="Boyle-van't Hoff relation for the osmometric behaviour of a cell: predicts the relative cell-content volume V_C/V_0 reached at osmotic equilibrium in an anisotonic medium, given the osmolarity (effective osmotic-pressure) ratio and the osmotically inactive volume fraction b = V_b/V_0. Assumes no net solute movement during equilibration (osmolyte content conserved). A plot of V_C/V_0 against pi_0/pi_C is linear with slope (1 - b) and intercept b; extrapolation to infinite pi_C gives the osmotically inactive volume (Boyle-van't Hoff plot, Feher Fig 2.9.3). Limiting behaviour: isotonic (pi_C = pi_0) gives V_C/V_0 = 1; strongly hypertonic (pi_C -> infinity) gives V_C/V_0 = b.",
    compute_func=compute_boyle_vant_hoff_relation,
    parameters=[
        Parameter(name='pi_0', description='Effective osmotic pressure (proportional to osmolarity) of the cell contents under isotonic conditions; reference state', units='Osm/L', symbol='\\pi_0', physiological_range=(0.05, 2)),
        Parameter(name='pi_C', description='Effective osmotic pressure (osmolarity) under the anisotonic condition; denominator of the ratio', units='Osm/L', symbol='\\pi_C', physiological_range=(0.05, 2)),
        Parameter(name='b', description="Osmotically inactive volume fraction V_b/V_0 (y-intercept of the Boyle-van't Hoff plot; e.g. 0.379 rabbit RBC, 0.392 human RBC)", units='dimensionless', symbol='V_b/V_0', physiological_range=(0, 1)),
    ],
    depends_on=[],
    metadata=EquationMetadata(source_unit=2, source_chapter='2.9',
                              source_section='WHAT STOPS OSMOTIC FLUID FLOW IN ANISOTONIC MEDIA?', page_reference=None,
                              textbook_equation_number='2.9.3'),
)
register_equation(boyle_vant_hoff_relation)

try:
    __all__ += ['boyle_vant_hoff_relation']
except NameError:
    __all__ = ['boyle_vant_hoff_relation']
