"""Consolidated module for renal.acid_base."""

"""
Net acid excretion (NAE) calculation.

Source: Quantitative Human Physiology 3rd Edition
Unit 7: Renal Physiology
"""

from scripts.base import (
    AtomicEquation, Parameter, EquationMetadata,
    EquationCategory, create_equation
)
from scripts.index import register_equation


def compute_net_acid_excretion(TA: float, NH4: float, HCO3_excreted: float) -> float:
    """
    Calculate net acid excretion.

    Args:
        TA: Titratable acid excretion (mEq/day)
        NH4: Ammonium excretion (mEq/day)
        HCO3_excreted: Bicarbonate excreted in urine (mEq/day)

    Returns:
        NAE: Net acid excretion (mEq/day), normally 50-100 mEq/day
    """
    return TA + NH4 - HCO3_excreted


# Create equation
net_acid_excretion = create_equation(
    id="net_acid_excretion",
    output_units='mEq/day',
    name="Net Acid Excretion",
    category=EquationCategory.RENAL,
    latex=r"NAE = TA + NH_4^+ - HCO_3^-_{excreted}",
    simplified="NAE = TA + NH4⁺ - HCO3⁻_excreted",
    description="Total acid excreted by kidney, matching daily metabolic acid production",
    compute_func=compute_net_acid_excretion,
    parameters=[
        Parameter(
            name="TA",
            description="Titratable acid (primarily phosphate buffer)",
            units="mEq/day",
            symbol="TA",
            physiological_range=(10, 50)
        ),
        Parameter(
            name="NH4",
            description="Ammonium excretion",
            units="mEq/day",
            symbol="NH_4^+",
            physiological_range=(20, 80)
        ),
        Parameter(
            name="HCO3_excreted",
            description="Bicarbonate excreted in urine",
            units="mEq/day",
            symbol="HCO_3^-_{excreted}",
            physiological_range=(0, 10)
        )
    ],
    depends_on=[],
    metadata=EquationMetadata(
        source_unit=7,
        source_chapter="7.7"
    )
)

# Register equation
register_equation(net_acid_excretion)

"""
New bicarbonate generation by the kidney.

Source: Quantitative Human Physiology 3rd Edition
Unit 7: Renal Physiology
"""


def compute_new_bicarbonate(TA: float, NH4: float) -> float:
    """
    Calculate new bicarbonate generated per day.

    Each H+ secreted and excreted as TA or NH4+ generates one new HCO3-.

    Args:
        TA: Titratable acid excretion (mEq/day)
        NH4: Ammonium excretion (mEq/day)

    Returns:
        new_HCO3: New bicarbonate generated (mEq/day)
    """
    return TA + NH4


# Create equation
new_bicarbonate_generation = create_equation(
    id="new_bicarbonate_generation",
    output_units='mEq/day',
    name="New Bicarbonate Generation",
    category=EquationCategory.RENAL,
    latex=r"New\ HCO_3^- = TA + NH_4^+",
    simplified="New HCO3⁻ = TA + NH4⁺",
    description="New bicarbonate generated by kidney via titratable acid and ammonium excretion",
    compute_func=compute_new_bicarbonate,
    parameters=[
        Parameter(
            name="TA",
            description="Titratable acid excretion",
            units="mEq/day",
            symbol="TA",
            physiological_range=(10, 50)
        ),
        Parameter(
            name="NH4",
            description="Ammonium excretion",
            units="mEq/day",
            symbol="NH_4^+",
            physiological_range=(20, 80)
        )
    ],
    depends_on=[],
    metadata=EquationMetadata(
        source_unit=7,
        source_chapter="7.7"
    )
)

# Register equation
register_equation(new_bicarbonate_generation)



# --- clinical additions (CICM, beyond Feher) ---

def compute_corrected_anion_gap(AG, albumin):
    """Albumin-corrected AG = AG + 0.25*(40 - albumin_g_L). Restores hidden gap in hypoalbuminaemia."""
    return AG + 0.25 * (40.0 - albumin)

corrected_anion_gap = create_equation(
    id='corrected_anion_gap',
    output_units='mEq/L',
    name='Albumin-Corrected Anion Gap',
    category=EquationCategory.RENAL,
    latex='AG_{corr} = AG + 0.25(40 - [alb])',
    simplified='AGc = AG + 0.25*(40-albumin)',
    description='Anion gap corrected for albumin (the dominant unmeasured anion): each 10 g/L fall in albumin lowers the apparent AG by ~2.5 mEq/L, masking a metabolic acidosis unless corrected.',
    compute_func=compute_corrected_anion_gap,
    parameters=[
        Parameter(name='AG', description='Measured anion gap (Na - Cl - HCO3)', units='mEq/L', symbol='AG', physiological_range=(2, 40)),
        Parameter(name='albumin', description='Serum albumin', units='g/L', symbol='alb', physiological_range=(10, 55)),
    ],
    depends_on=["anion_gap"],
    produces='cAG',
    metadata=EquationMetadata(source_unit=0, source_chapter='clinical',
                              source_section="Clinical standard (CICM/ICU); beyond Feher's text", page_reference=None),
)
register_equation(corrected_anion_gap)


def compute_delta_ratio(AG, HCO3):
    """Delta ratio = (AG-12)/(24-HCO3). <0.4 non-AG acidosis; ~1-2 pure HAGMA; >2 concurrent metabolic alkalosis/resp acidosis."""
    return (AG - 12.0) / (24.0 - HCO3)

delta_ratio = create_equation(
    id='delta_ratio',
    output_units='dimensionless',
    name='Delta Ratio',
    category=EquationCategory.RENAL,
    latex='\\Delta ratio = \\frac{AG-12}{24-[HCO_3^-]}',
    simplified='delta_ratio = (AG-12)/(24-HCO3)',
    description='Delta-gap ratio comparing the rise in anion gap to the fall in bicarbonate; detects a mixed metabolic disorder superimposed on a high-anion-gap metabolic acidosis.',
    compute_func=compute_delta_ratio,
    parameters=[
        Parameter(name='AG', description='Anion gap', units='mEq/L', symbol='AG', physiological_range=(12, 40)),
        Parameter(name='HCO3', description='Bicarbonate', units='mmol/L', symbol='HCO3', physiological_range=(2, 24)),
    ],
    depends_on=["anion_gap"],
    produces='delta_ratio',
    metadata=EquationMetadata(source_unit=0, source_chapter='clinical',
                              source_section="Clinical standard (CICM/ICU); beyond Feher's text", page_reference=None),
)
register_equation(delta_ratio)

try:
    __all__ += ['corrected_anion_gap', 'delta_ratio']
except NameError:
    __all__ = ['corrected_anion_gap', 'delta_ratio']
